import { ReactQueryProvider } from "./ReactQueryProvider";
import "./globals.css";

export const metadata = {
  title: "OnlineStore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className="">{children}</body>
      </html>
    </ReactQueryProvider>
  );
}
